export type CountryOption = { value: string; label: string; callingCode?: string }

function isoToFlagEmoji(iso: string): string {
  const s = iso.trim().toUpperCase()
  if (s.length !== 2) return ''
  const a = s.charCodeAt(0)
  const b = s.charCodeAt(1)
  if (a < 65 || a > 90 || b < 65 || b > 90) return ''
  return String.fromCodePoint(0x1f1e6 + (a - 65), 0x1f1e6 + (b - 65))
}

const callingCodeByIso: Record<string, string> = {
  AD: '376',
  AE: '971',
  AF: '93',
  AG: '1268',
  AI: '1264',
  AL: '355',
  AM: '374',
  AO: '244',
  AQ: '672',
  AR: '54',
  AS: '1684',
  AT: '43',
  AU: '61',
  AW: '297',
  AX: '358',
  AZ: '994',
  BA: '387',
  BB: '1246',
  BD: '880',
  BE: '32',
  BF: '226',
  BG: '359',
  BH: '973',
  BI: '257',
  BJ: '229',
  BL: '590',
  BM: '1441',
  BN: '673',
  BO: '591',
  BQ: '599',
  BR: '55',
  BS: '1242',
  BT: '975',
  BV: '47',
  BW: '267',
  BY: '375',
  BZ: '501',
  CA: '1',
  CC: '61',
  CD: '243',
  CF: '236',
  CG: '242',
  CH: '41',
  CI: '225',
  CK: '682',
  CL: '56',
  CM: '237',
  CN: '86',
  CO: '57',
  CR: '506',
  CU: '53',
  CV: '238',
  CW: '599',
  CX: '61',
  CY: '357',
  CZ: '420',
  DE: '49',
  DJ: '253',
  DK: '45',
  DM: '1767',
  DO: '1849',
  DZ: '213',
  EC: '593',
  EE: '372',
  EG: '20',
  EH: '212',
  ER: '291',
  ES: '34',
  ET: '251',
  FI: '358',
  FJ: '679',
  FK: '500',
  FM: '691',
  FO: '298',
  FR: '33',
  GA: '241',
  GB: '44',
  GD: '1473',
  GE: '995',
  GF: '594',
  GG: '44',
  GH: '233',
  GI: '350',
  GL: '299',
  GM: '220',
  GN: '224',
  GP: '590',
  GQ: '240',
  GR: '30',
  GS: '500',
  GT: '502',
  GU: '1671',
  GW: '245',
  GY: '592',
  HK: '852',
  HM: '672',
  HN: '504',
  HR: '385',
  HT: '509',
  HU: '36',
  ID: '62',
  IE: '353',
  IL: '972',
  IM: '44',
  IN: '91',
  IO: '246',
  IQ: '964',
  IR: '98',
  IS: '354',
  IT: '39',
  JE: '44',
  JM: '1876',
  JO: '962',
  JP: '81',
  KE: '254',
  KG: '996',
  KH: '855',
  KI: '686',
  KM: '269',
  KN: '1869',
  KP: '850',
  KR: '82',
  KW: '965',
  KY: '345',
  KZ: '7',
  LA: '856',
  LB: '961',
  LC: '1758',
  LI: '423',
  LK: '94',
  LR: '231',
  LS: '266',
  LT: '370',
  LU: '352',
  LV: '371',
  LY: '218',
  MA: '212',
  MC: '377',
  MD: '373',
  ME: '382',
  MF: '590',
  MG: '261',
  MH: '692',
  MK: '389',
  ML: '223',
  MM: '95',
  MN: '976',
  MO: '853',
  MP: '1670',
  MQ: '596',
  MR: '222',
  MS: '1664',
  MT: '356',
  MU: '230',
  MV: '960',
  MW: '265',
  MX: '52',
  MY: '60',
  MZ: '258',
  NA: '264',
  NC: '687',
  NE: '227',
  NF: '672',
  NG: '234',
  NI: '505',
  NL: '31',
  NO: '47',
  NP: '977',
  NR: '674',
  NU: '683',
  NZ: '64',
  OM: '968',
  PA: '507',
  PE: '51',
  PF: '689',
  PG: '675',
  PH: '63',
  PK: '92',
  PL: '48',
  PM: '508',
  PN: '64',
  PR: '1939',
  PS: '970',
  PT: '351',
  PW: '680',
  PY: '595',
  QA: '974',
  RE: '262',
  RO: '40',
  RS: '381',
  RU: '7',
  RW: '250',
  SA: '966',
  SB: '677',
  SC: '248',
  SD: '249',
  SE: '46',
  SG: '65',
  SH: '290',
  SI: '386',
  SJ: '47',
  SK: '421',
  SL: '232',
  SM: '378',
  SN: '221',
  SO: '252',
  SR: '597',
  SS: '211',
  ST: '239',
  SV: '503',
  SX: '1721',
  SY: '963',
  SZ: '268',
  TC: '1649',
  TD: '235',
  TF: '262',
  TG: '228',
  TH: '66',
  TJ: '992',
  TK: '690',
  TL: '670',
  TM: '993',
  TN: '216',
  TO: '676',
  TR: '90',
  TT: '1868',
  TV: '688',
  TW: '886',
  TZ: '255',
  UA: '380',
  UG: '256',
  UM: '1',
  US: '1',
  UY: '598',
  UZ: '998',
  VA: '379',
  VC: '1784',
  VE: '58',
  VG: '1284',
  VI: '1340',
  VN: '84',
  VU: '678',
  WF: '681',
  WS: '685',
  YE: '967',
  YT: '262',
  ZA: '27',
  ZM: '260',
  ZW: '263',
}

export function formatCountryForBackend(countryISO2: string): string {
  const iso = countryISO2.trim().toUpperCase()
  if (!iso) return ''
  const callingCode = callingCodeByIso[iso]
  if (!callingCode) return iso
  return `${callingCode}_${iso}`
}

const rawCountryOptions: CountryOption[] = [
  { value: 'AF', label: 'AF - Afghanistan' },
  { value: 'AL', label: 'AL - Albania' },
  { value: 'DZ', label: 'DZ - Algeria' },
  { value: 'AS', label: 'AS - American Samoa' },
  { value: 'AD', label: 'AD - Andorra' },
  { value: 'AO', label: 'AO - Angola' },
  { value: 'AI', label: 'AI - Anguilla' },
  { value: 'AQ', label: 'AQ - Antarctica' },
  { value: 'AG', label: 'AG - Antigua and Barbuda' },
  { value: 'AR', label: 'AR - Argentina' },
  { value: 'AM', label: 'AM - Armenia' },
  { value: 'AW', label: 'AW - Aruba' },
  { value: 'AU', label: 'AU - Australia' },
  { value: 'AT', label: 'AT - Austria' },
  { value: 'AZ', label: 'AZ - Azerbaijan' },
  { value: 'BS', label: 'BS - Bahamas' },
  { value: 'BH', label: 'BH - Bahrain' },
  { value: 'BD', label: 'BD - Bangladesh' },
  { value: 'BB', label: 'BB - Barbados' },
  { value: 'BY', label: 'BY - Belarus' },
  { value: 'BE', label: 'BE - Belgium' },
  { value: 'BZ', label: 'BZ - Belize' },
  { value: 'BJ', label: 'BJ - Benin' },
  { value: 'BM', label: 'BM - Bermuda' },
  { value: 'BT', label: 'BT - Bhutan' },
  { value: 'BO', label: 'BO - Bolivia' },
  { value: 'BQ', label: 'BQ - Bonaire, Sint Eustatius and Saba' },
  { value: 'BA', label: 'BA - Bosnia and Herzegovina' },
  { value: 'BW', label: 'BW - Botswana' },
  { value: 'BV', label: 'BV - Bouvet Island' },
  { value: 'BR', label: 'BR - Brazil' },
  { value: 'IO', label: 'IO - British Indian Ocean Territory' },
  { value: 'BN', label: 'BN - Brunei Darussalam' },
  { value: 'BG', label: 'BG - Bulgaria' },
  { value: 'BF', label: 'BF - Burkina Faso' },
  { value: 'BI', label: 'BI - Burundi' },
  { value: 'CV', label: 'CV - Cabo Verde' },
  { value: 'KH', label: 'KH - Cambodia' },
  { value: 'CM', label: 'CM - Cameroon' },
  { value: 'CA', label: 'CA - Canada' },
  { value: 'KY', label: 'KY - Cayman Islands' },
  { value: 'CF', label: 'CF - Central African Republic' },
  { value: 'TD', label: 'TD - Chad' },
  { value: 'CL', label: 'CL - Chile' },
  { value: 'CN', label: 'CN - China' },
  { value: 'CX', label: 'CX - Christmas Island' },
  { value: 'CC', label: 'CC - Cocos (Keeling) Islands' },
  { value: 'CO', label: 'CO - Colombia' },
  { value: 'KM', label: 'KM - Comoros' },
  { value: 'CG', label: 'CG - Congo' },
  { value: 'CD', label: 'CD - Congo (Democratic Republic of the)' },
  { value: 'CK', label: 'CK - Cook Islands' },
  { value: 'CR', label: 'CR - Costa Rica' },
  { value: 'CI', label: "CI - Côte d'Ivoire" },
  { value: 'HR', label: 'HR - Croatia' },
  { value: 'CU', label: 'CU - Cuba' },
  { value: 'CW', label: 'CW - Curaçao' },
  { value: 'CY', label: 'CY - Cyprus' },
  { value: 'CZ', label: 'CZ - Czechia' },
  { value: 'DK', label: 'DK - Denmark' },
  { value: 'DJ', label: 'DJ - Djibouti' },
  { value: 'DM', label: 'DM - Dominica' },
  { value: 'DO', label: 'DO - Dominican Republic' },
  { value: 'EC', label: 'EC - Ecuador' },
  { value: 'EG', label: 'EG - Egypt' },
  { value: 'SV', label: 'SV - El Salvador' },
  { value: 'GQ', label: 'GQ - Equatorial Guinea' },
  { value: 'ER', label: 'ER - Eritrea' },
  { value: 'EE', label: 'EE - Estonia' },
  { value: 'SZ', label: 'SZ - Eswatini' },
  { value: 'ET', label: 'ET - Ethiopia' },
  { value: 'FK', label: 'FK - Falkland Islands (Malvinas)' },
  { value: 'FO', label: 'FO - Faroe Islands' },
  { value: 'FJ', label: 'FJ - Fiji' },
  { value: 'FI', label: 'FI - Finland' },
  { value: 'FR', label: 'FR - France' },
  { value: 'GF', label: 'GF - French Guiana' },
  { value: 'PF', label: 'PF - French Polynesia' },
  { value: 'TF', label: 'TF - French Southern Territories' },
  { value: 'GA', label: 'GA - Gabon' },
  { value: 'GM', label: 'GM - Gambia' },
  { value: 'GE', label: 'GE - Georgia' },
  { value: 'DE', label: 'DE - Germany' },
  { value: 'GH', label: 'GH - Ghana' },
  { value: 'GI', label: 'GI - Gibraltar' },
  { value: 'GR', label: 'GR - Greece' },
  { value: 'GL', label: 'GL - Greenland' },
  { value: 'GD', label: 'GD - Grenada' },
  { value: 'GP', label: 'GP - Guadeloupe' },
  { value: 'GU', label: 'GU - Guam' },
  { value: 'GT', label: 'GT - Guatemala' },
  { value: 'GG', label: 'GG - Guernsey' },
  { value: 'GN', label: 'GN - Guinea' },
  { value: 'GW', label: 'GW - Guinea-Bissau' },
  { value: 'GY', label: 'GY - Guyana' },
  { value: 'HT', label: 'HT - Haiti' },
  { value: 'HM', label: 'HM - Heard Island and McDonald Islands' },
  { value: 'VA', label: 'VA - Holy See' },
  { value: 'HN', label: 'HN - Honduras' },
  { value: 'HK', label: 'HK - Hong Kong' },
  { value: 'HU', label: 'HU - Hungary' },
  { value: 'IS', label: 'IS - Iceland' },
  { value: 'IN', label: 'IN - India' },
  { value: 'ID', label: 'ID - Indonesia' },
  { value: 'IR', label: 'IR - Iran (Islamic Republic of)' },
  { value: 'IQ', label: 'IQ - Iraq' },
  { value: 'IE', label: 'IE - Ireland' },
  { value: 'IM', label: 'IM - Isle of Man' },
  { value: 'IL', label: 'IL - Israel' },
  { value: 'IT', label: 'IT - Italy' },
  { value: 'JM', label: 'JM - Jamaica' },
  { value: 'JP', label: 'JP - Japan' },
  { value: 'JE', label: 'JE - Jersey' },
  { value: 'JO', label: 'JO - Jordan' },
  { value: 'KZ', label: 'KZ - Kazakhstan' },
  { value: 'KE', label: 'KE - Kenya' },
  { value: 'KI', label: 'KI - Kiribati' },
  { value: 'KP', label: "KP - Korea (Democratic People's Republic of)" },
  { value: 'KR', label: 'KR - Korea, Republic of' },
  { value: 'KW', label: 'KW - Kuwait' },
  { value: 'KG', label: 'KG - Kyrgyzstan' },
  { value: 'LA', label: "LA - Lao People's Democratic Republic" },
  { value: 'LV', label: 'LV - Latvia' },
  { value: 'LB', label: 'LB - Lebanon' },
  { value: 'LS', label: 'LS - Lesotho' },
  { value: 'LR', label: 'LR - Liberia' },
  { value: 'LY', label: 'LY - Libya' },
  { value: 'LI', label: 'LI - Liechtenstein' },
  { value: 'LT', label: 'LT - Lithuania' },
  { value: 'LU', label: 'LU - Luxembourg' },
  { value: 'MO', label: 'MO - Macao' },
  { value: 'MG', label: 'MG - Madagascar' },
  { value: 'MW', label: 'MW - Malawi' },
  { value: 'MY', label: 'MY - Malaysia' },
  { value: 'MV', label: 'MV - Maldives' },
  { value: 'ML', label: 'ML - Mali' },
  { value: 'MT', label: 'MT - Malta' },
  { value: 'MH', label: 'MH - Marshall Islands' },
  { value: 'MQ', label: 'MQ - Martinique' },
  { value: 'MR', label: 'MR - Mauritania' },
  { value: 'MU', label: 'MU - Mauritius' },
  { value: 'YT', label: 'YT - Mayotte' },
  { value: 'MX', label: 'MX - Mexico' },
  { value: 'FM', label: 'FM - Micronesia (Federated States of)' },
  { value: 'MD', label: 'MD - Moldova, Republic of' },
  { value: 'MC', label: 'MC - Monaco' },
  { value: 'MN', label: 'MN - Mongolia' },
  { value: 'ME', label: 'ME - Montenegro' },
  { value: 'MS', label: 'MS - Montserrat' },
  { value: 'MA', label: 'MA - Morocco' },
  { value: 'MZ', label: 'MZ - Mozambique' },
  { value: 'MM', label: 'MM - Myanmar' },
  { value: 'NA', label: 'NA - Namibia' },
  { value: 'NR', label: 'NR - Nauru' },
  { value: 'NP', label: 'NP - Nepal' },
  { value: 'NL', label: 'NL - Netherlands' },
  { value: 'NC', label: 'NC - New Caledonia' },
  { value: 'NZ', label: 'NZ - New Zealand' },
  { value: 'NI', label: 'NI - Nicaragua' },
  { value: 'NE', label: 'NE - Niger' },
  { value: 'NG', label: 'NG - Nigeria' },
  { value: 'NU', label: 'NU - Niue' },
  { value: 'NF', label: 'NF - Norfolk Island' },
  { value: 'MK', label: 'MK - North Macedonia' },
  { value: 'MP', label: 'MP - Northern Mariana Islands' },
  { value: 'NO', label: 'NO - Norway' },
  { value: 'OM', label: 'OM - Oman' },
  { value: 'PK', label: 'PK - Pakistan' },
  { value: 'PW', label: 'PW - Palau' },
  { value: 'PS', label: 'PS - Palestine, State of' },
  { value: 'PA', label: 'PA - Panama' },
  { value: 'PG', label: 'PG - Papua New Guinea' },
  { value: 'PY', label: 'PY - Paraguay' },
  { value: 'PE', label: 'PE - Peru' },
  { value: 'PH', label: 'PH - Philippines' },
  { value: 'PN', label: 'PN - Pitcairn' },
  { value: 'PL', label: 'PL - Poland' },
  { value: 'PT', label: 'PT - Portugal' },
  { value: 'PR', label: 'PR - Puerto Rico' },
  { value: 'QA', label: 'QA - Qatar' },
  { value: 'RE', label: 'RE - Réunion' },
  { value: 'RO', label: 'RO - Romania' },
  { value: 'RU', label: 'RU - Russian Federation' },
  { value: 'RW', label: 'RW - Rwanda' },
  { value: 'BL', label: 'BL - Saint Barthélemy' },
  { value: 'SH', label: 'SH - Saint Helena, Ascension and Tristan da Cunha' },
  { value: 'KN', label: 'KN - Saint Kitts and Nevis' },
  { value: 'LC', label: 'LC - Saint Lucia' },
  { value: 'MF', label: 'MF - Saint Martin (French part)' },
  { value: 'PM', label: 'PM - Saint Pierre and Miquelon' },
  { value: 'VC', label: 'VC - Saint Vincent and the Grenadines' },
  { value: 'WS', label: 'WS - Samoa' },
  { value: 'SM', label: 'SM - San Marino' },
  { value: 'ST', label: 'ST - Sao Tome and Principe' },
  { value: 'SA', label: 'SA - Saudi Arabia' },
  { value: 'SN', label: 'SN - Senegal' },
  { value: 'RS', label: 'RS - Serbia' },
  { value: 'SC', label: 'SC - Seychelles' },
  { value: 'SL', label: 'SL - Sierra Leone' },
  { value: 'SG', label: 'SG - Singapore' },
  { value: 'SX', label: 'SX - Sint Maarten (Dutch part)' },
  { value: 'SK', label: 'SK - Slovakia' },
  { value: 'SI', label: 'SI - Slovenia' },
  { value: 'SB', label: 'SB - Solomon Islands' },
  { value: 'SO', label: 'SO - Somalia' },
  { value: 'ZA', label: 'ZA - South Africa' },
  { value: 'GS', label: 'GS - South Georgia and the South Sandwich Islands' },
  { value: 'SS', label: 'SS - South Sudan' },
  { value: 'ES', label: 'ES - Spain' },
  { value: 'LK', label: 'LK - Sri Lanka' },
  { value: 'SD', label: 'SD - Sudan' },
  { value: 'SR', label: 'SR - Suriname' },
  { value: 'SJ', label: 'SJ - Svalbard and Jan Mayen' },
  { value: 'SE', label: 'SE - Sweden' },
  { value: 'CH', label: 'CH - Switzerland' },
  { value: 'SY', label: 'SY - Syrian Arab Republic' },
  { value: 'TW', label: 'TW - Taiwan, Province of China' },
  { value: 'TJ', label: 'TJ - Tajikistan' },
  { value: 'TZ', label: 'TZ - Tanzania, United Republic of' },
  { value: 'TH', label: 'TH - Thailand' },
  { value: 'TL', label: 'TL - Timor-Leste' },
  { value: 'TG', label: 'TG - Togo' },
  { value: 'TK', label: 'TK - Tokelau' },
  { value: 'TO', label: 'TO - Tonga' },
  { value: 'TT', label: 'TT - Trinidad and Tobago' },
  { value: 'TN', label: 'TN - Tunisia' },
  { value: 'TR', label: 'TR - Türkiye' },
  { value: 'TM', label: 'TM - Turkmenistan' },
  { value: 'TC', label: 'TC - Turks and Caicos Islands' },
  { value: 'TV', label: 'TV - Tuvalu' },
  { value: 'UG', label: 'UG - Uganda' },
  { value: 'UA', label: 'UA - Ukraine' },
  { value: 'AE', label: 'AE - United Arab Emirates' },
  { value: 'GB', label: 'GB - United Kingdom' },
  { value: 'US', label: 'US - United States of America' },
  { value: 'UM', label: 'UM - United States Minor Outlying Islands' },
  { value: 'UY', label: 'UY - Uruguay' },
  { value: 'UZ', label: 'UZ - Uzbekistan' },
  { value: 'VU', label: 'VU - Vanuatu' },
  { value: 'VE', label: 'VE - Venezuela (Bolivarian Republic of)' },
  { value: 'VN', label: 'VN - Viet Nam' },
  { value: 'VG', label: 'VG - Virgin Islands (British)' },
  { value: 'VI', label: 'VI - Virgin Islands (U.S.)' },
  { value: 'WF', label: 'WF - Wallis and Futuna' },
  { value: 'EH', label: 'EH - Western Sahara' },
  { value: 'YE', label: 'YE - Yemen' },
  { value: 'ZM', label: 'ZM - Zambia' },
  { value: 'ZW', label: 'ZW - Zimbabwe' },
]

export const countryOptions: CountryOption[] = rawCountryOptions.map((o) => {
  const name = o.label.startsWith(`${o.value} - `) ? o.label.slice(`${o.value} - `.length) : o.label
  const flag = isoToFlagEmoji(o.value)
  const callingCode = callingCodeByIso[o.value]
  const callingText = callingCode ? ` (+${callingCode})` : ''
  return {
    ...o,
    callingCode,
    label: `${flag ? `${flag} ` : ''}${o.value}${callingText} - ${name}`,
  }
})
